name: "Build and deploy"

on: [push]

env:
  NETCORE_VERSION: '3.1.103'
  PUBLISH_PATH: "./publish"
  DEPLOY_PATH: "./WaIIerKb/publish"
  AZURE_WEBAPP_NAME: "WaIIerKb"
  WORKING_DIRECTORY: "./WaIIerKb"




jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1

    - name: Restore
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: dotnet restore

    - name: Build
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: dotnet build --no-restore -c Release

    - name: Publish
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: dotnet publish --no-build -c Release --output ${{ env.PUBLISH_PATH }}

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE}}
        package: ${{ env.DEPLOY_PATH }}

    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.DEPLOY_PATH }}
